- hosts: webservers
  become: yes
  tasks:
    # 1. 更新套件
    - name: 更新 apt 套件列表
      apt:
        update_cache: yes

    # 2. 安裝 Node.js, npm, git
    - name: 安裝 Node.js、npm、git
      apt:
        name: [nodejs, npm, git]
        state: present

    - name: 複製 Git Repo
      git:
        repo: https://github.com/kaisensei1206/kaiweiPersonalWeb.git  # ← 改成你的 GitHub 專案網址
        dest: /etc/systemd/system/myapp.service                 # ← 如果要換資料夾名稱可改
        version: main                           # ← 如果不是 main branch，要改成 branch 名稱

    - name: 建立 systemd 服務檔
      copy:
        dest: /etc/systemd/system/myapp.service # ← "myapp" 可以換成你的應用名稱
        content: |
          [Unit]
          Description=myWebsite           # ← 描述可以改成你的專案名
          After=network.target

          [Service]
          ExecStart=/usr/bin/node /home/ubuntu/app/server.js        # ← 如果啟動指令不同要改，例如 `node server.js`
          WorkingDirectory=ExecStart=/home/ubuntu/app # ← 跟上面 git dest 相同
          Restart=always
          User=ubuntu                           # ← 跑服務的使用者（通常 ubuntu 就好）
          Environment=NODE_ENV=production       # ← 如果要加其他環境變數在這裡
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=myapp
          [Install]
          WantedBy=multi-user.target


    - name: 重新載入 systemd
      systemd:
        daemon_reload: yes

    - name: 啟動並啟用 myapp 服務
      systemd:
        name: myapp                             # ← 跟上面 systemd 檔案名稱一致
        state: started
        enabled: yes
        
    # 7. 安裝 Caddy
    - name: 安裝 Caddy 所需工具
      apt:
        name: [debian-keyring, debian-archive-keyring, apt-transport-https, curl]
        state: present

    - name: 新增 Caddy GPG 金鑰
      shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      args:
        warn: false

    - name: 新增 Caddy 軟體源
      shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        | tee /etc/apt/sources.list.d/caddy-stable.list
      args:
        warn: false

    - name: 更新套件並安裝 Caddy
      apt:
        update_cache: yes
        name: caddy
        state: present

    # 8. 設定 Caddyfile
    - name: 設定 Caddy 反向代理
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          :first. {
              reverse_proxy localhost:8080
          }

    # 9. 重啟 Caddy
    - name: 重啟 Caddy
      systemd:
        name: caddy
        state: restarted
        enabled: yes